# Generated by Django 5.2.7 on 2025-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbeneEats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_breakdown', models.TextField(blank=True)),
                ('change_returned', models.TextField(blank=True)),
            ],
        ),
    ]
